cache_path: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/dataset
exp_name: vit
log_dir: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/exp/${exp_name}/${now:%Y-%m-%d-%H-%M-%S}
endecoder_ckpt: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/weights/EnDecoder_new.ckpt
seed: 114514

trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 1

dataloader:
  batch_size: 64
  shuffle: True
  num_workers: 8


