cache_path: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/dataset
exp_name: vit
log_dir: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/exp/${exp_name}/${now:%Y-%m-%d-%H-%M-%S}
endecoder_ckpt: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/weights/EnDecoder_new.ckpt
ckpt_path: /data15/jinkun.liu.2502/CodeSpace/FlameDiff/exp/vit/2025-03-11-16-47-46/vit/version_0/checkpoints/flame-epoch=1999-val_loss=0.01.ckpt
seed: 0

sensors: [[20, 95], [70, 95], [110, 80], [110, 110], [160, 75], [160, 120], [200, 75], [200, 120]]

flame_agent:
  params:
    endecoder_ckpt: ${endecoder_ckpt}
    sensors: ${sensors}
    # ckpt_path: ${ckpt_path}
    
trainer:
  max_epochs: 2000
  check_val_every_n_epoch: 50
  log_every_n_steps: 1
  strategy: ddp
  gradient_clip_val: 1.0

dataloader:
  batch_size: 32
  shuffle: True
  num_workers: 8


